#!/bin/bash
#PBS -N log_BalticLBC 
#PBS -l select=85
#PBS -l walltime=0:10:00
#PBS -A n01-CLASS
## mail alert at (b)eginning, (e)nd and (a)bortion of execution
#PBS -q standard

## LOAD MODULES
module load cray-libsci/16.11.1
module load cray-mpich/7.5.5
module load cray-netcdf-hdf5parallel/4.4.1.1
module load cray-hdf5-parallel/1.10.0.1

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
OCEANCORES=1752
ulimit -c unlimited
ulimit -s unlimited

cd $PBS_O_WORKDIR
rm -f core log_* ocean.output output.namelist.dyn
aprun -b -n 12 -N 1 ./xios_server.exe : -n $OCEANCORES -N 24 ./nemo_riv7.exe

